[profile.default]
solc_version = '0.8.15'
auto_detect_solc = false

remappings = [
    "forge-std/=lib/forge-std/src/",
    "v2-core/=lib/v2-core/contracts/",
    "v2-periphery/=lib/v2-periphery/contracts/",
]

