[profile.default]
solc_version = '0.8.15'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200 # Default amount
ffi = true
remappings = [
    "forge-std/=lib/ds-test/src/",
    "v2-core/=lib/v2-core/contracts/",
]

